// Mocks generated by Mockito 5.4.6 from annotations
// in tuuuur_flutter/test/api/theme_api_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tuuuur_flutter/api/api_client.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i2.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.ApiResponse<Map<String, dynamic>>> getJson(
    String? path, {
    Map<String, String>? headers,
    bool? auth = false,
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getJson,
              [path],
              {#headers: headers, #auth: auth, #timeout: timeout},
            ),
            returnValue:
                _i3.Future<_i2.ApiResponse<Map<String, dynamic>>>.value(
                  _FakeApiResponse_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #getJson,
                      [path],
                      {#headers: headers, #auth: auth, #timeout: timeout},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i2.ApiResponse<Map<String, dynamic>>>);

  @override
  _i3.Future<_i2.ApiResponse<Map<String, dynamic>>> postJson(
    String? path, {
    Object? body,
    Map<String, String>? headers,
    bool? auth = false,
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postJson,
              [path],
              {#body: body, #headers: headers, #auth: auth, #timeout: timeout},
            ),
            returnValue:
                _i3.Future<_i2.ApiResponse<Map<String, dynamic>>>.value(
                  _FakeApiResponse_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #postJson,
                      [path],
                      {
                        #body: body,
                        #headers: headers,
                        #auth: auth,
                        #timeout: timeout,
                      },
                    ),
                  ),
                ),
          )
          as _i3.Future<_i2.ApiResponse<Map<String, dynamic>>>);

  @override
  _i3.Future<_i2.ApiResponse<Map<String, dynamic>>> putJson(
    String? path, {
    Object? body,
    Map<String, String>? headers,
    bool? auth = false,
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putJson,
              [path],
              {#body: body, #headers: headers, #auth: auth, #timeout: timeout},
            ),
            returnValue:
                _i3.Future<_i2.ApiResponse<Map<String, dynamic>>>.value(
                  _FakeApiResponse_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #putJson,
                      [path],
                      {
                        #body: body,
                        #headers: headers,
                        #auth: auth,
                        #timeout: timeout,
                      },
                    ),
                  ),
                ),
          )
          as _i3.Future<_i2.ApiResponse<Map<String, dynamic>>>);

  @override
  _i3.Future<_i2.ApiResponse<Map<String, dynamic>>> delete(
    String? path, {
    Map<String, String>? headers,
    bool? auth = false,
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {#headers: headers, #auth: auth, #timeout: timeout},
            ),
            returnValue:
                _i3.Future<_i2.ApiResponse<Map<String, dynamic>>>.value(
                  _FakeApiResponse_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #delete,
                      [path],
                      {#headers: headers, #auth: auth, #timeout: timeout},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i2.ApiResponse<Map<String, dynamic>>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
