// Mocks generated by Mockito 5.4.6 from annotations
// in tuuuur_flutter/test/pages/auth/auth_login_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tuuuur_flutter/api/api_client.dart' as _i2;
import 'package:tuuuur_flutter/api/auth_api_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApi extends _i1.Mock implements _i3.AuthApi {
  MockAuthApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponse<_i3.RegisterResult>> register({
    required String? email,
    required String? nickName,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #email: email,
              #nickName: nickName,
              #password: password,
            }),
            returnValue: _i4.Future<_i2.ApiResponse<_i3.RegisterResult>>.value(
              _FakeApiResponse_0<_i3.RegisterResult>(
                this,
                Invocation.method(#register, [], {
                  #email: email,
                  #nickName: nickName,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i3.RegisterResult>>);

  @override
  _i4.Future<_i2.ApiResponse<bool>> login({
    required String? login,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#login: login, #password: password}),
            returnValue: _i4.Future<_i2.ApiResponse<bool>>.value(
              _FakeApiResponse_0<bool>(
                this,
                Invocation.method(#login, [], {
                  #login: login,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<bool>>);

  @override
  _i4.Future<_i2.ApiResponse<_i3.AuthSession>> loginWithGoogle({
    required String? idToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loginWithGoogle, [], {#idToken: idToken}),
            returnValue: _i4.Future<_i2.ApiResponse<_i3.AuthSession>>.value(
              _FakeApiResponse_0<_i3.AuthSession>(
                this,
                Invocation.method(#loginWithGoogle, [], {#idToken: idToken}),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i3.AuthSession>>);

  @override
  _i4.Future<_i2.ApiResponse<bool>> passwordForgot({required String? login}) =>
      (super.noSuchMethod(
            Invocation.method(#passwordForgot, [], {#login: login}),
            returnValue: _i4.Future<_i2.ApiResponse<bool>>.value(
              _FakeApiResponse_0<bool>(
                this,
                Invocation.method(#passwordForgot, [], {#login: login}),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<bool>>);

  @override
  _i4.Future<_i2.ApiResponse<bool>> passwordReset({
    required String? login,
    required String? code,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#passwordReset, [], {
              #login: login,
              #code: code,
              #password: password,
            }),
            returnValue: _i4.Future<_i2.ApiResponse<bool>>.value(
              _FakeApiResponse_0<bool>(
                this,
                Invocation.method(#passwordReset, [], {
                  #login: login,
                  #code: code,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<bool>>);

  @override
  _i4.Future<_i2.ApiResponse<_i3.AuthSession>> verify2fa({
    required String? login,
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verify2fa, [], {#login: login, #code: code}),
            returnValue: _i4.Future<_i2.ApiResponse<_i3.AuthSession>>.value(
              _FakeApiResponse_0<_i3.AuthSession>(
                this,
                Invocation.method(#verify2fa, [], {#login: login, #code: code}),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i3.AuthSession>>);

  @override
  _i4.Future<_i2.ApiResponse<_i3.AuthSession>> refreshToken({
    required String? bearer,
    required String? refreshToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, [], {
              #bearer: bearer,
              #refreshToken: refreshToken,
            }),
            returnValue: _i4.Future<_i2.ApiResponse<_i3.AuthSession>>.value(
              _FakeApiResponse_0<_i3.AuthSession>(
                this,
                Invocation.method(#refreshToken, [], {
                  #bearer: bearer,
                  #refreshToken: refreshToken,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i3.AuthSession>>);

  @override
  _i4.Future<_i2.ApiResponse<_i3.UserDto>> me() =>
      (super.noSuchMethod(
            Invocation.method(#me, []),
            returnValue: _i4.Future<_i2.ApiResponse<_i3.UserDto>>.value(
              _FakeApiResponse_0<_i3.UserDto>(this, Invocation.method(#me, [])),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i3.UserDto>>);

  @override
  _i4.Future<_i2.ApiResponse<bool>> updateAvatarBase64({
    required String? base64,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateAvatarBase64, [], {#base64: base64}),
            returnValue: _i4.Future<_i2.ApiResponse<bool>>.value(
              _FakeApiResponse_0<bool>(
                this,
                Invocation.method(#updateAvatarBase64, [], {#base64: base64}),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<bool>>);

  @override
  _i4.Future<_i2.ApiResponse<bool>> changePassword({
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i4.Future<_i2.ApiResponse<bool>>.value(
              _FakeApiResponse_0<bool>(
                this,
                Invocation.method(#changePassword, [], {
                  #currentPassword: currentPassword,
                  #newPassword: newPassword,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<bool>>);

  @override
  _i4.Future<_i2.ApiResponse<bool>> deleteMe() =>
      (super.noSuchMethod(
            Invocation.method(#deleteMe, []),
            returnValue: _i4.Future<_i2.ApiResponse<bool>>.value(
              _FakeApiResponse_0<bool>(this, Invocation.method(#deleteMe, [])),
            ),
          )
          as _i4.Future<_i2.ApiResponse<bool>>);

  @override
  _i4.Future<_i2.ApiResponse<_i3.UserDto>> updateNickname({
    required String? nickname,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateNickname, [], {#nickname: nickname}),
            returnValue: _i4.Future<_i2.ApiResponse<_i3.UserDto>>.value(
              _FakeApiResponse_0<_i3.UserDto>(
                this,
                Invocation.method(#updateNickname, [], {#nickname: nickname}),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i3.UserDto>>);
}
