name: CD - Master (Production)

on:
  push:
    branches:
      - master

jobs:
  build-mobile:
    uses: ./.github/workflows/cd-build-mobile.yml
    with:
      environment_name: "Production"
      version_tag: "latest"
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
