name: CD - Release (Preprod)

on:
  push:
    branches:
      - release

jobs:
  build-mobile:
    uses: ./.github/workflows/cd-build-mobile.yml
    with:
      environment_name: 'Preprod'
      version_tag: 'preprod'
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
